---
Name: mysite
After:
  - 'framework/*'
  - 'cms/*'
---
# YAML configuration for SilverStripe
# See http://doc.silverstripe.org/framework/en/topics/configuration
# Caution: Indentation through two spaces, not tabs
SSViewer:
  theme: 'aris'
i18n:
  default_locale: 'en_US'
TranslatableDataObject:
  locales:
    - 'en_US'
    - 'ru_RU'
