<?php

namespace BB\Machine;

/** 
 * This class has been auto-generated by the SS importer module
 * 
 * @property string Expression 
 * @property string Name 
 * @method \HasManyList Machines() 
 */

class Variable extends \DataObject {
    
    private static $singular_name = "Variable";
    
    private static $plural_name = "Variables";
    
    private static $db = array(
        'Name' => 'Varchar',
        'Expression' => 'Enum("None,PrintingSheetsCount,SignatureCount,StockSheetCount","None")',
    );

    private static $belongs_many_many = array(
        'Machines' => 'BB\Machine',
    );

    private static $summary_fields = array(
        'Name', 'Expression',
    );

    private static $searchable_fields = array(
        'Name', 'Expression'
    );
    


}
