<?php

namespace PC;

/** 
 * This class has been auto-generated by the SS importer module
 * 
 * @property string Name 
 * @property float Price 
 */

class AdditionalService extends \DataObject {
    
    private static $singular_name = "Additional Service";
    
    private static $plural_name = "Additional Services";
    
    private static $db = array(
        'Name' => 'Varchar',
        'Price' => 'Decimal(16)',
    );

    


}
