<?php

namespace PC;

/** 
 * This class has been auto-generated by the SS importer module
 * 
 * @property integer BindingID 
 * @property integer FlowID 
 * @property bool IsVisible 
 * @property string Name 
 * @property int SortOrder 
 * @method Binding Binding() 
 * @method \HasManyList CalculationRequests() 
 * @method Flow Flow() 
 */

class BindingOption extends \DataObject {
    
    private static $singular_name = "Binding Option";
    
    private static $plural_name = "Binding Options";
    
    private static $db = array(
        'Name' => 'Varchar(50)',
        'IsVisible' => 'Boolean',
        'SortOrder' => 'Int',
    );

    private static $has_many = array(
        'CalculationRequests' => 'PC\CalculationRequest',
    );

    private static $has_one = array(
        'Binding' => 'PC\Binding',
    );

    


}
