<?php

namespace PC;
use Utils\FrontEnd;

/** 
 * This class has been auto-generated by the SS importer module
 * 
 * @property integer BindingTypeID 
 * @property int HeightMax 
 * @property int HeightMin 
 * @property bool IsVisible 
 * @property string Name 
 * @property int PagesMax 
 * @property int PagesMin 
 * @property int SortOrder 
 * @property float Weight 
 * @method \HasManyList BindingOptions() 
 * @method BindingType BindingType() 
 * @method \HasManyList CalculationRequests() 
 */

class Binding extends \DataObject {
    
    private static $singular_name = "Binding";
    
    private static $plural_name = "Bindings";
    
    private static $db = array(
        'Name' => 'Varchar',
        'PagesMin' => 'Int',
        'PagesMax' => 'Int',
        'HeightMin' => 'Int',
        'HeightMax' => 'Int',
        'Weight' => 'Decimal',
        'IsVisible' => 'Boolean',
        'SortOrder' => 'Int',
    );

    private static $has_many = array(
        'BindingOptions' => 'PC\BindingOption',
        'CalculationRequests' => 'PC\CalculationRequest',
    );

    private static $has_one = array(
        'BindingType' => 'PC\BindingType',
    );

    public function forTemplate() {
        return $this->Name;
    }
    

    /* ----- Class content ----- */

	public function getBindingOptionOrdered() {
        return FrontEnd::filter(
            $this->BindingOptions()->sort('SortOrder ASC')
        );
	}

    /* ----- Table content ----- */

    public static function getBindingOrdered() {
        return FrontEnd::filter(
            BindingType::get()->sort('SortOrder ASC')
        );
    }

}
