<?php

namespace PC;

/** 
 * This class has been auto-generated by the SS importer module
 * 
 * @property bool HasBwPages 
 * @property bool HasColorPages 
 * @property string Name 
 * @method \HasManyList CalculationRequests() 
 */

class BookColorType extends \DataObject {
    
    private static $singular_name = "Book Color Type";
    
    private static $plural_name = "Book Color Types";
    
    private static $db = array(
        'Name' => 'Varchar(50)',
        'HasColorPages' => 'Boolean',
        'HasBwPages' => 'Boolean',
    );

    private static $has_many = array(
        'CalculationRequests' => 'PC\CalculationRequest',
    );

    


}
