<?php

namespace PC;
use BB\PaperDensity;
use BB\PaperType;

/** 
 * This class has been auto-generated by the SS importer module
 * 
 * @property integer BindingID 
 * @property integer BindingOptionID 
 * @property integer BookColorTypeID 
 * @property integer BookFormatID 
 * @property int BookNumber1 
 * @property int BookNumber2 
 * @property int BookNumber3 
 * @property integer BookPaperStockSheetID
 * @property int BwPageNumber 
 * @property int ColorPageNumber 
 * @property string CompanyName 
 * @property integer CoverDecorationID 
 * @property integer CoverPaperStockSheetID
 * @property integer CoverTypeID 
 * @property integer DeliveryTypeID 
 * @property integer FileFormatID 
 * @property integer PrintQualityID 
 * @property integer UserID
 * @property string UserComments
 * @property string UserEmail 
 * @property string UserName 
 * @property string UserPhone 
 * @method \ManyManyList AdditionalServices() 
 * @method Binding Binding() 
 * @method BindingOption BindingOption() 
 * @method BookColorType BookColorType() 
 * @method BookFormat BookFormat() 
 * @method PaperStockSheet BookPaperStockSheet()
 * @method \HasManyList|Calculation[] Calculations()
 * @method CoverDecoration CoverDecoration() 
 * @method PaperStockSheet CoverPaperStockSheet()
 * @method CoverType CoverType() 
 * @method DeliveryType DeliveryType() 
 * @method FileFormat FileFormat() 
 * @method PrintQuality PrintQuality() 
 * @method User User()
 * @method PaperType BookPaperType()
 * @method PaperDensity BookPaperDensity()
 * @method PaperType CoverPaperType()
 * @method PaperDensity CoverPaperDensity()
 * @method PaperType ColorPaperType()
 * @method PaperDensity ColorPaperDensity()
 * @property integer BookPaperTypeID
 * @property integer BookPaperDensityID
 * @property integer CoverPaperTypeID
 * @property integer CoverPaperDensityID
 * @property integer ColorPaperTypeID
 * @property integer ColorPaperDensityID
 */

class CalculationRequest extends \DataObject {
    
    private static $singular_name = "Calculation Request";
    
    private static $plural_name = "Calculation Requests";
    
    private static $db = array(
        'BwPageNumber' => 'Int',
        'ColorPageNumber' => 'Int',
        'BookNumber1' => 'Int',
        'BookNumber2' => 'Int',
        'BookNumber3' => 'Int',
        'UserEmail' => 'Varchar(255)',
        'UserName' => 'Varchar(255)',
        'CompanyName' => 'Varchar(255)',
        'UserPhone' => 'Varchar(255)',
        'UserComments' => 'Varchar(1024)',
    );

    private static $has_many = array(
        'Calculations' => 'PC\Calculation',
    );

    private static $has_one = array(
        'Binding' => 'PC\Binding',
        'BindingOption' => 'PC\BindingOption',
        'BookFormat' => 'PC\BookFormat',
        'BookColorType' => 'PC\BookColorType',
        'CoverType' => 'PC\CoverType',
//        'BookPaperStockSheet' => 'PC\PaperStockSheet',
//        'CoverPaperStockSheet' => 'PC\PaperStockSheet',
        'PrintQuality' => 'PC\PrintQuality',
        'DeliveryType' => 'PC\DeliveryType',
        'FileFormat' => 'PC\FileFormat',
        'CoverDecoration' => 'PC\CoverDecoration',
        'User' => 'PC\User',

        'BookPaperType' => 'BB\PaperType',
        'BookPaperDensity' => 'BB\PaperDensity',

        'CoverPaperType' => 'BB\PaperType',
        'CoverPaperDensity' => 'BB\PaperDensity',

        'ColorPaperType' => 'BB\PaperType',
        'ColorPaperDensity' => 'BB\PaperDensity',
    );

    private static $many_many = array(
        'AdditionalServices' => 'PC\AdditionalService',
    );

    

    /* ----- Class content ----- */

	public function getCalculationsOrderedDesc() {
        return $this->Calculations()
            ->innerJoin('PC\OrderDeadline','"PC\OrderDeadline".ID="PC\Calculation".OrderDeadlineID')
            ->sort('NumberOfDays DESC');
	}

    /* ----- Table content ----- */

    public static function getBindingsOrdered() {
        return Binding::get()
            ->innerJoin('PC\BindingType','PC\BindingType.ID=PC\Binding.BindingType')
            ->sort('"PC\BindingType"."Name" DESC, "PC\Binding"."Name" ASC');
    }

}
