<?php

namespace PC;

/** 
 * This class has been auto-generated by the SS importer module
 * 
 * @property bool IsColor 
 * @property bool IsSingleSide 
 * @property string Name 
 * @method \ManyManyList BindingTypes() 
 * @method \HasManyList CalculationRequests() 
 */

class CoverType extends \DataObject {
    
    private static $singular_name = "Cover Type";
    
    private static $plural_name = "Cover Types";
    
    private static $db = array(
        'Name' => 'Varchar(50)',
        'IsColor' => 'Boolean',
        'IsSingleSide' => 'Boolean',
    );

    private static $has_many = array(
        'CalculationRequests' => 'PC\CalculationRequest',
    );

    private static $many_many = array(
        'BindingTypes' => 'PC\BindingType',
    );

    


}
