<?php

namespace PC;
use Utils\FrontEnd;

/** 
 * This class has been auto-generated by the SS importer module
 * 
 * @property integer BindingTypeID 
 * @property bool IsVisible 
 * @property string Name 
 * @property int SortOrder 
 * @method BindingType BindingType() 
 * @method \HasManyList CoverDecorations() 
 */

class CoverDecorationType extends \DataObject {
    
    private static $singular_name = "Cover Decoration Type";
    
    private static $plural_name = "Cover Decoration Types";
    
    private static $db = array(
        'Name' => 'Varchar',
        'IsVisible' => 'Boolean',
        'SortOrder' => 'Int',
    );

    private static $has_many = array(
        'CoverDecorations' => 'PC\CoverDecoration',
    );

    private static $has_one = array(
        'BindingType' => 'PC\BindingType',
    );


    public function forTemplate() {
        return $this->Name;
    }

    public function getTitle() {
        return $this->Name;
    }


    /* ----- Class content ----- */

	
	public function getCoverDecorationOrdered() {
        return FrontEnd::filter(
            $this->CoverDecorations()->sort('SortOrder ASC')
        );
	}


}
