<?php

namespace PC;

/** 
 * This class has been auto-generated by the SS importer module
 * 
 * @property integer CurrencyID 
 * @property float Rate 
 * @property int RateDate 
 * @method Currency Currency() 
 */

class CurrencyRate extends \DataObject {
    
    private static $singular_name = "Currency Rate";
    
    private static $plural_name = "Currency Rates";
    
    private static $db = array(
        'Rate' => 'Decimal(16)',
        'RateDate' => 'Varchar(12)',
    );

    private static $has_one = array(
        'Currency' => 'PC\Currency',
    );

    

    /* ----- Table content ----- */

    
//    public static function getInstance()
//    {
//        return Doctrine_Core::getTable('CurrencyRate');
//    }

}
