<?php

namespace PC;

/** 
 * This class has been auto-generated by the SS importer module
 * 
 * @property string Name 
 * @method \HasManyList CurrencyRates() 
 */

class Currency extends \DataObject {
    
    private static $singular_name = "Currency";
    
    private static $plural_name = "Currencies";
    
    private static $db = array(
        'Name' => 'Varchar(50)',
    );

    private static $has_many = array(
        'CurrencyRates' => 'PC\CurrencyRate',
    );

    

    /* ----- Table content ----- */

    
//    public static function getInstance()
//    {
//        return Doctrine_Core::getTable('Currency');
//    }

}
