<?php

namespace PC;

/** 
 * This class has been auto-generated by the SS importer module
 * 
 * @property string Name 
 * @property float Price 
 * @method \HasManyList CalculationRequests() 
 */

class FileFormat extends \DataObject {
    
    private static $singular_name = "File Format";
    
    private static $plural_name = "File Formats";
    
    private static $db = array(
        'Name' => 'Varchar(50)',
        'Price' => 'Decimal(16)',
    );

    private static $has_many = array(
        'CalculationRequests' => 'PC\CalculationRequest',
    );

    


}
