<?php

namespace PC;

/** 
 * This class has been auto-generated by the SS importer module
 * 
 * @property string Name 
 * @property int Priority 
 * @method \HasManyList Jobs() 
 */

class JobPriority extends \DataObject {
    
    private static $singular_name = "Job Priority";
    
    private static $plural_name = "Job Priorities";
    
    private static $db = array(
        'Name' => 'Varchar(50)',
        'Priority' => 'Int',
    );

    private static $has_many = array(
        'Jobs' => 'PC\Job',
    );

    

    /* ----- Table content ----- */

    
//    public static function getInstance()
//    {
//        return Doctrine_Core::getTable('JobPriority');
//    }

}
