<?php

namespace PC;

/** 
 * This class has been auto-generated by the SS importer module
 * 
 * @property bool IsFinal 
 * @property string Name 
 * @method \HasManyList Jobs() 
 */

class JobStatus extends \DataObject {
    
    private static $singular_name = "Job Status";
    
    private static $plural_name = "Job Statuses";
    
    private static $db = array(
        'Name' => 'Varchar(50)',
        'IsFinal' => 'Boolean',
    );

    private static $has_many = array(
        'Jobs' => 'PC\Job',
    );

    

    /* ----- Table content ----- */

    
//    public static function getInstance()
//    {
//        return Doctrine_Core::getTable('JobStatus');
//    }

}
