<?php

namespace PC;

/** 
 * This class has been auto-generated by the SS importer module
 * 
 * @property float HourRate 
 * @property integer MachineID 
 * @property integer OrderDeadlineID 
 * @method Machine Machine() 
 * @method OrderDeadline OrderDeadline() 
 */

class MachineHourRate extends \DataObject {
    
    private static $singular_name = "Machine Hour Rate";
    
    private static $plural_name = "Machine Hour Rates";
    
    private static $db = array(
        'Title' => 'Varchar(128)',
        'HourRate' => 'Decimal(16)',
    );

    private static $has_one = array(
        'Machine' => 'PC\Machine',
        'OrderDeadline' => 'PC\OrderDeadline',
    );

    

    /* ----- Table content ----- */

    
//    public static function getInstance()
//    {
//        return Doctrine_Core::getTable('MachineHourRate');
//    }

}
