<?php

namespace PC;

use BB\Chromaticity;
use BB\PaperDensity;
use BB\PaperDensityGroup;
use BB\PaperFormat;
use BB\PaperType;
use Utils\FrontEnd;
use Utils\GriedFieldExtraFieldsUtils;

/**
 * This class has been auto-generated by the SS importer module
 *
 * @property float FittingFormCost
 * @property int FormFittingSeconds
 * @property int FormFittingSheets
 * @property float HourRate
 * @property float NonPrintableWidth
 * @property float NonPrintableHeight
 * @property bool IsColor
 * @property bool IsCostByClick
 * @property bool IsSingleSide
 * @property int MachineFittingSeconds
 * @property int MachineFittingSheets
 * @property integer MachineTypeID
 * @property int MaxX
 * @property int MaxY
 * @property string Name
 * @property float PrintCost
 * @property integer PrintQualityID
 * @property integer VariableID
 * @method \HasManyList Jobs()
 * @method \HasManyList MachineHourRates()
 * @method MachineType MachineType()
 * @method \ManyManyList|MachinePaperWeight[] MachinePaperWeights()
 * @method \ManyManyList|PaperType[] MachinePaperTypes()
 * @method \ManyManyList|Chromaticity[] MachineChromaticities()
 * @method \ManyManyList|PaperFormat[] MachinePaperFormats()
 * @method \ManyManyList|PaperDensityGroup[] PaperDensityGroups()
 * @method PrintQuality PrintQuality()
 * @method Variable Variable()
 */

class Machine extends \DataObject {

    private static $singular_name = "Machine";

    private static $plural_name = "Machines";

    private static $db = array(
        'Name' => 'Varchar(50)',
        'MachineFittingSeconds' => 'Int',
        'MachineFittingSheets' => 'Int',
        'FormFittingSeconds' => 'Int',
        'FormFittingSheets' => 'Int',
        'FittingFormCost' => 'Decimal(16)',
        'PrintCost' => 'Decimal(16)',
        'HourRate' => 'Decimal(16)',
        'IsSingleSide' => 'Boolean',
        'IsColor' => 'Boolean',
        'IsCostByClick' => 'Boolean',
        'NonPrintableWidth' => 'Float',
        'NonPrintableHeight' => 'Float',
    );

    private static $has_many = array(
        'MachineHourRates' => 'PC\MachineHourRate',
        'Jobs' => 'PC\Job',
    );

    private static $has_one = array(
        'PrintQuality' => 'PC\PrintQuality',
        'MachineType' => 'PC\MachineType',
        'Variable' => 'PC\Variable',
    );

    private static $many_many = array(
        'PaperDensityGroups' => 'BB\PaperDensityGroup',
        'MachinePaperWeights' => 'PC\MachinePaperWeight',
        'MachinePaperFormats' => 'BB\PaperFormat',
        'MachinePaperTypes' => 'BB\PaperType',
        'MachineChromaticities' => 'BB\Chromaticity',
    );

    public function getCMSFields() {
        $fields = parent::getCMSFields();
//        $fields = GriedFieldExtraFieldsUtils::create($this)->getCMSFields();

        foreach ($this->PaperDensityGroups() as $group) {
            foreach ($group->PaperDensities() as $density) {
                $MachinePaperWeight = $this->MachinePaperWeights()->filter(
                    'PaperDensityID', $density->ID
                )->first();
                if (!$MachinePaperWeight || !$MachinePaperWeight->exists()) {
                    $MachinePaperWeight = new MachinePaperWeight();
                    $MachinePaperWeight->PaperDensityID = $density->ID;
                    $MachinePaperWeight->write();
                    $this->MachinePaperWeights()->add($MachinePaperWeight);
                }
            }
        }
//        $fields->replaceField(
//            'MachinePaperWeights',
//            GriedFieldExtraFieldsUtils::create($this)->getExtraGridField('MachinePaperWeights')
//        );

        return $fields;
    }

    public function getPrintableFormat(PaperFormat $source_format) {
        $format = new PaperFormat();
        $format->Width = $source_format->Width - $this->NonPrintableWidth;
        $format->Height = $source_format->Height - $this->NonPrintableHeight;
        return $format;
    }

    public function getAvailablePropertyIDs($name,$params=null) {
        $name = 'getAvailable'.$name.'IDs';
        return method_exists($this,$name) ? $this->{$name}($params) : array();
    }

    public function getAvailablePaperDensityIDs($params=null) {
        $machineDensityIDs = $this->MachinePaperWeights()->map('PaperDensityID','PaperDensityID')->toArray();
        $stockSheetDensityIDs = FrontEnd::getFor('PC\PaperStockSheet')->map('PaperDensityID','PaperDensityID')->toArray();
        return array_intersect($machineDensityIDs,$stockSheetDensityIDs);
    }

    public function getAvailablePaperTypeIDs($params=null) {
        return $this->MachinePaperTypes()->map('ID','ID')->toArray();
    }

    public function getAvailablePaperFormatIDs($params=null) {
        $formats = array();
        if (isset($params['product'])) {
            /** @var Product $product */
            $product = $params['product'];
            foreach ($product->PaperFormats() as $format) {
                $productFormatWithBleeds = $product->getFormatWithBleeds($format);
                /** @var PaperFormat $machineFormat */
                foreach ($this->MachinePaperFormats() as $machineFormat) {
                    $printableFormat = $this->getPrintableFormat($machineFormat);
                    if ($printableFormat->getQuantityFormatSpreadedOut($productFormatWithBleeds)>0) {
                        $formats[$format->ID] = $format->ID;
                    }
                }
            }
        }
//        \Debug::dump($formats);
        return $formats;
//        return $formats ? $formats : $this->MachinePaperFormats()->map('ID','ID')->toArray();
    }

    public function getAvailableChromaticityIDs($params=null) {
        return $this->MachineChromaticities()->map('ID','ID')->toArray();
    }

    public function calculateProductRequestPrice(ProductRequest $pr, FlowOperationItem $flowOperationItem = null) {
        $arr = array('price'=>-1,'log'=>'','log_error'=>'','strict'=>false);

        $format = $pr->getFormatWithBleeds();
        foreach ($this->MachinePaperFormats() as $machinePaperFormat) {
            $mci = new MachineCalculationItem();
            $mci->ProductRequestID = $pr->ID;
            $mci->MachineID = $this->ID;
            if ($flowOperationItem) $mci->FlowOperationItemID = $flowOperationItem->ID;
            $mci->write();

            $printableFormat = $this->getPrintableFormat($machinePaperFormat);
            $this->logPriceTrace($mci,'------------ Machine Printable Format -> '.$printableFormat->getDimensionString());
            $this->logPriceTrace($mci,'------------ Machine Paper Format -> '.$machinePaperFormat->getDimensionString());
            $q = $printableFormat->getQuantityFormatSpreadedOut($format);
            $this->logPriceTrace($mci,'Product Format -> '.$format->Title);
            $this->logPriceTrace($mci,'Product per Machine Paper Format = '.$q);
            if (!($q>0)) {
                $mci->Status = 'Fail';
                $mci->StatusMessage = 'Product paper formet is bigger than printable area';
                $this->logErrorTrace($mci,$mci->StatusMessage,true);
                continue;
            }
            /** @var PaperStockSheet[]|\DataList $sheets */
            $sheets = FrontEnd::getFor('PC\PaperStockSheet')->filter(array(
                    'PaperTypeID'=>$pr->PaperTypeID,
                    'PaperDensityID'=>$pr->PaperDensityID,
            ));
            if (!$sheets || !$sheets->exists()) {
                $mci->Status = 'Fail';
                $mci->StatusMessage = 'No Paper Stock Sheets available';
                $this->logErrorTrace($mci,$mci->StatusMessage,true);
                continue;
            }
            $printingSheetsCount = ceil($pr->Circulation/$q) * ceil($pr->PagesCount/2);
            $this->logPriceTrace($mci,'Printing Sheets Count = '.$printingSheetsCount);
            $signatureCount = ceil(ceil($pr->PagesCount/2) / $q);
            $this->logPriceTrace($mci,'Signature Count = '.$signatureCount);
            $printingSheetsCount += $signatureCount * $this->MachineFittingSheets;
            $this->logPriceTrace($mci,'Total Printing Sheets Count = '.$printingSheetsCount);

            // -------------- Paper Price --------------
            $lowestSheetPrice = -1;
            foreach ($sheets as $sheet) {
                $this->logPriceTrace($mci,'------------ Paper Stock Sheet -> '.$sheet->Name);
                $qm = $sheet->PaperFormat()->getQuantityFormatSpreadedOut($machinePaperFormat);
                $this->logPriceTrace($mci,'Machine Paper Format per Stock Sheet = '.$qm);
                if (!($qm>0)) continue;
                $sheetsCount = ceil($printingSheetsCount / $qm);
                $this->logPriceTrace($mci,'Stock Sheet count = '.$sheetsCount);
                $price = $sheetsCount * $sheet->Cost;
                $this->logPriceTrace($mci,'Paper Stock Sheet price = '.$price);
                if (!($lowestSheetPrice>0) || $price<$lowestSheetPrice) {
                    $lowestSheetPrice = $price;
                    $mci->PaperStockSheetID = $sheet->ID;
                }
            }

            // -------------- Total Print Price --------------
            if ($this->IsCostByClick) {
                continue;
            } else {
                $fitting_time = ($this->MachineFittingSeconds + $this->FormFittingSeconds * $signatureCount)/3600;
                $this->logPriceTrace($mci,'Fitting time = '.$fitting_time);
                $machinePaperWeight = $this->MachinePaperWeights()->filter('PaperDensityID',$pr->PaperDensityID)->first();
                if ($machinePaperWeight && $machinePaperWeight->exists()) {
                    $printing_time = $printingSheetsCount / $machinePaperWeight->PrintSpeed;
                    $this->logPriceTrace($mci,'Printing time = '.$printing_time);
                    $printing_time_price = ($fitting_time + $printing_time) * $this->HourRate;
                    $this->logPriceTrace($mci,'Fitting & Printing time price = '.$printing_time_price);
                } else {
                    $arr['log_error'] .= "\r\n".'Couldn\'t find Machine Paper Weight = '
                        .$this->Name.' '.$machinePaperFormat->getDimensionString();
                }
            }
            $plates_price = $this->FittingFormCost * $signatureCount;
            $this->logPriceTrace($mci,'Plates price = '.$plates_price);
            $price = $lowestSheetPrice + $printing_time_price + $plates_price;
            $mci->Status = 'Success';
            $mci->Price = $price;
            $this->logPriceTrace($mci,'Total price = '.$price,true);

        }
        /** @var MachineCalculationItem $mciLowest */
        $mciLowest = $pr->MachineCalculationItems()->sort('Price ASC')->where('Price > 0')->first();
        return $mciLowest ? $mciLowest->Price : false;
    }

    private function logTrace(MachineCalculationItem $mci, $message, $where='Price', $write = false){
        $mci->{$where.'Trace'} = $mci->{$where.'Trace'} . "\r\n".$message;
        if ($write) $mci->write();
    }

    private function logPriceTrace(MachineCalculationItem $mci, $message, $write = false){
        $this->logTrace($mci, $message, 'Price', $write);
    }

    private function logErrorTrace(MachineCalculationItem $mci, $message, $write = false){
        $this->logTrace($mci, $message, 'Error', $write);
    }


}










