<?php

namespace PC;

/** 
 * This class has been auto-generated by the SS importer module
 * 
 * @property string Name 
 * @property int NumberOfDays 
 * @property float PricePercent 
 * @method \HasManyList Calculations() 
 * @method \HasManyList MachineHourRates() 
 */

class OrderDeadline extends \DataObject {
    
    private static $singular_name = "Order Deadline";
    
    private static $plural_name = "Order Deadlines";
    
    private static $db = array(
        'Name' => 'Varchar(50)',
        'NumberOfDays' => 'Int',
        'PricePercent' => 'Decimal',
    );

    private static $has_many = array(
        'Calculations' => 'PC\Calculation',
        'MachineHourRates' => 'PC\MachineHourRate',
    );

    


}
