<?php

namespace PC;

/** 
 * This class has been auto-generated by the SS importer module
 * 
 * @property string Name
 * @property string Description
 * @property string DescriptionForUser
 * @property bool IsUserEmailNotify
 * @property int Code
 * @property string NotificationEmails
 * @property string EmailFrom
 * @property string EmailSubject
 * @property string EmailBody
 * @method \HasManyList ClientOrders()
 */

class OrderStatus extends \DataObject {
    
    private static $singular_name = "Order Status";
    
    private static $plural_name = "Order Statuses";
    
    private static $db = array(
        'Name' => 'Varchar(50)',
        'Description' => 'Text',
        'DescriptionForUser' => 'HTMLText',
        'IsUserEmailNotify' => 'Boolean(0)',
        'Code' => 'Int',
        'NotificationEmails' => 'Text',
        'EmailFrom' => 'Varchar(512)',
        'EmailSubject' => 'Text',
        'EmailBody' => 'HTMLText',
    );

    private static $has_many = array(
        'ClientOrders' => 'PC\ClientOrder',
    );

    private  static $summary_fields = array(
        'Name', 'Code', 'Description',
    );

    protected function onBeforeWrite() {
        $this->EmailSubject = str_replace('%24','$',$this->EmailSubject);
        $this->EmailBody = str_replace('%24','$',$this->EmailBody);
        parent::onBeforeWrite();
    }

    /* ----- Table content ----- */

    public static function getDefaultStatusId() {
    	return 1;
    }

}
