<?php

namespace PC;

/** 
 * This class has been auto-generated by the SS importer module
 * 
 * @method \HasManyList Jobs() 
 */

class Order extends \DataObject {
    
    private static $singular_name = "Order";
    
    private static $plural_name = "Orders";
    
    private static $has_many = array(
        'Jobs' => 'PC\Job',
    );

    


}
