<?php

namespace PC;

/** 
 * This class has been auto-generated by the SS importer module
 * 
 * @property string Name 
 * @method \HasManyList CalculationRequests() 
 * @method \HasManyList Machines() 
 */

class PrintQuality extends \DataObject {
    
    private static $singular_name = "Print Quality";
    
    private static $plural_name = "Print Qualities";
    
    private static $db = array(
        'Name' => 'Varchar(50)',
    );

    private static $has_many = array(
        'Machines' => 'PC\Machine',
        'CalculationRequests' => 'PC\CalculationRequest',
    );

    

    /* ----- Table content ----- */


	/**
	 * gets active print quality types (which has at least one machine)
	 */
	public static function getActiveTypes()	{
        return PrintQuality::get()
            ->where('EXISTS ('.
                'SELECT "PC\Machine"."ID" '.
                'FROM "PC\Machine" '.
                'WHERE "PC\Machine"."PrintQualityID" = "PC\PrintQuality"."ID"'.
                ')');
	}

}
