<?php

namespace PC;

/** 
 * This class has been auto-generated by the SS importer module
 * 
 * @property string Expression 
 * @property string Name 
 * @method \HasManyList Machines() 
 */

class Variable extends \DataObject {
    
    private static $singular_name = "Variable";
    
    private static $plural_name = "Variables";
    
    private static $db = array(
        'Name' => 'Varchar',
        'Expression' => 'Varchar',
    );

    private static $has_many = array(
        'Machines' => 'PC\Machine',
    );

    


}
