<?php

namespace PC;


/** 
 * This class has been auto-generated by the SS importer module
 * 
 * @property string Name 
 * @method \HasManyList BindingOptions() 
 * @method \HasManyList CoverDecorations() 
 * @method \ManyManyList|MachineType[] MachineTypes()
 * @method \ManyManyList|MachineClass[] MachineClasses()
 */

class FlowOperation extends \DataObject {

    private static $singular_name = "Flow Operation";
    
    private static $plural_name = "FlowOperations";
    
    private static $many_many = array(
        'MachineTypes' => 'PC\MachineType',
        'MachineClasses' => 'PC\MachineClass',
    );

    private static $belongs_many_many = array(
        'Flows' => 'PC\Flow'
    );

    private static $db = array(
        'Name' => 'Varchar',
    );

    private static $has_many = array(
    );

    private static $summary_fields = array(
        'Name',
    );

    private static $searchable_fields = array(
        'Name',
    );

    public function getCMSFields() {
        $fields = parent::getCMSFields();

//        $field = After($field,'Name');

        return $fields;
    }


    public function getAvailablePropertyIDs($name,$params=null) {
        $arr = array();
        foreach ($this->MachineTypes() as $type) {
            $arr = array_merge($arr, $type->getAvailablePropertyIDs($name,$params));
        }
        return $arr;
    }
    
    
	
    
        

}
