<?php

namespace PC;

/** 
 * This class has been auto-generated by the SS importer module
 * 
 * @property string Name
 * @method \HasManyList|Product[] Products()
 * @method \ManyManyList|FlowOperation[] FlowOperations()
 */

class Flow extends \DataObject {
    
    private static $singular_name = "Flow";
    
    private static $plural_name = "Flows";
    
    private static $many_many = array(
        'FlowOperations' => 'PC\FlowOperation',
    );

    private static $belongs_many_many = array(
    );

    private static $db = array(
        'Name' => 'Varchar',
    );

    private static $has_many = array(
        'Products' => 'PC\Product',
    );

    private static $summary_fields = array(
        'Name',
    );

    private static $searchable_fields = array(
        'Name',
    );



    
        

}
