<?php

namespace PC;

/** 
 * This class has been auto-generated by the SS importer module
 * 
 * @property string Name
 * @property string MachineClass
 * @method \ManyManyList|FlowOperation[] FlowOperations()
 */

class MachineClass extends \DataObject {

    private static $singular_name = "Machine Class";
    
    private static $plural_name = "Machine Classes";
    
    private static $many_many = array(
    );

    private static $belongs_many_many = array(
        'FlowOperations' => 'PC\FlowOperation'
    );

    private static $db = array(
        'Name' => 'Varchar(128)',
        'MachineClass' => 'Varchar(128)',
    );

    private static $has_many = array(
    );

    private static $summary_fields = array(
        'Name',
    );

    private static $searchable_fields = array(
        'Name',
    );

    public function getCMSFields() {
        $fields = parent::getCMSFields();

        $return = array(''=>'None');
        foreach (\ClassInfo::subclassesFor('BB\Machine') as $key => $value) {
            $ex = explode('\\',$value);
            $return[$key] = end($ex);
        }

        $fields->replaceField(
            'MachineClass',
            new \DropdownField('MachineClass',$this->fieldLabel('MachineClass'),$return,$this->MachineClass)
        );

        return $fields;
    }

}
